name: ci

"on":
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [16]

    steps:
      - name: Checkout 🛎
        id: checkout
        uses: actions/checkout@master

      - name: Setup node env 🏗
        id: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          check-latest: true

      - name: Install dependencies 👨🏻‍💻
        id: install-npm-dependencies
        run: npm install

      - name: Run linter 👀
        id: run-linter
        run: npm run lint
